// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/common_msg/login.proto

package common_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientRandom string `protobuf:"bytes,1,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`
}

func (x *HandshakeInitRequest) Reset() {
	*x = HandshakeInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeInitRequest) ProtoMessage() {}

func (x *HandshakeInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeInitRequest.ProtoReflect.Descriptor instead.
func (*HandshakeInitRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeInitRequest) GetClientRandom() string {
	if x != nil {
		return x.ClientRandom
	}
	return ""
}

type HandshakeInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode   int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ServerRandom string `protobuf:"bytes,2,opt,name=server_random,json=serverRandom,proto3" json:"server_random,omitempty"`
	PublicKey    string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *HandshakeInitResponse) Reset() {
	*x = HandshakeInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeInitResponse) ProtoMessage() {}

func (x *HandshakeInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeInitResponse.ProtoReflect.Descriptor instead.
func (*HandshakeInitResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeInitResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HandshakeInitResponse) GetServerRandom() string {
	if x != nil {
		return x.ServerRandom
	}
	return ""
}

func (x *HandshakeInitResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type HandshakeEstablishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedKey []byte `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
}

func (x *HandshakeEstablishedRequest) Reset() {
	*x = HandshakeEstablishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeEstablishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeEstablishedRequest) ProtoMessage() {}

func (x *HandshakeEstablishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeEstablishedRequest.ProtoReflect.Descriptor instead.
func (*HandshakeEstablishedRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeEstablishedRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type HandshakeEstablishedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *HandshakeEstablishedResponse) Reset() {
	*x = HandshakeEstablishedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeEstablishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeEstablishedResponse) ProtoMessage() {}

func (x *HandshakeEstablishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeEstablishedResponse.ProtoReflect.Descriptor instead.
func (*HandshakeEstablishedResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeEstablishedResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type AccountLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *AccountLoginRequest) Reset() {
	*x = AccountLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginRequest) ProtoMessage() {}

func (x *AccountLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginRequest.ProtoReflect.Descriptor instead.
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{4}
}

func (x *AccountLoginRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AccountLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode  int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Ip         string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port       int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	UserId     uint64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionKey string `protobuf:"bytes,5,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
}

func (x *AccountLoginResponse) Reset() {
	*x = AccountLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginResponse) ProtoMessage() {}

func (x *AccountLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginResponse.ProtoReflect.Descriptor instead.
func (*AccountLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{5}
}

func (x *AccountLoginResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *AccountLoginResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AccountLoginResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AccountLoginResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountLoginResponse) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type ClientLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionKey string `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Version    int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClientLoginRequest) Reset() {
	*x = ClientLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLoginRequest) ProtoMessage() {}

func (x *ClientLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLoginRequest.ProtoReflect.Descriptor instead.
func (*ClientLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{6}
}

func (x *ClientLoginRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClientLoginRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *ClientLoginRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ClientLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	UserId    uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version   int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	IsNewbie  bool   `protobuf:"varint,4,opt,name=is_newbie,json=isNewbie,proto3" json:"is_newbie,omitempty"`
	Ammo      uint32 `protobuf:"varint,5,opt,name=ammo,proto3" json:"ammo,omitempty"`
	Grenades  uint32 `protobuf:"varint,6,opt,name=grenades,proto3" json:"grenades,omitempty"`
}

func (x *ClientLoginResponse) Reset() {
	*x = ClientLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLoginResponse) ProtoMessage() {}

func (x *ClientLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLoginResponse.ProtoReflect.Descriptor instead.
func (*ClientLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{7}
}

func (x *ClientLoginResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ClientLoginResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClientLoginResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientLoginResponse) GetIsNewbie() bool {
	if x != nil {
		return x.IsNewbie
	}
	return false
}

func (x *ClientLoginResponse) GetAmmo() uint32 {
	if x != nil {
		return x.Ammo
	}
	return 0
}

func (x *ClientLoginResponse) GetGrenades() uint32 {
	if x != nil {
		return x.Grenades
	}
	return 0
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 uint64 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 string `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{8}
}

func (x *EchoRequest) GetValue1() uint64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *EchoRequest) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 uint64 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 string `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{9}
}

func (x *EchoResponse) GetValue1() uint64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *EchoResponse) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

type AsyncEchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 uint64 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 string `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *AsyncEchoRequest) Reset() {
	*x = AsyncEchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncEchoRequest) ProtoMessage() {}

func (x *AsyncEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncEchoRequest.ProtoReflect.Descriptor instead.
func (*AsyncEchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{10}
}

func (x *AsyncEchoRequest) GetValue1() uint64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *AsyncEchoRequest) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

type AsyncEchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 uint64 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 string `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *AsyncEchoResponse) Reset() {
	*x = AsyncEchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_msg_login_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncEchoResponse) ProtoMessage() {}

func (x *AsyncEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_msg_login_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncEchoResponse.ProtoReflect.Descriptor instead.
func (*AsyncEchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_msg_login_proto_rawDescGZIP(), []int{11}
}

func (x *AsyncEchoResponse) GetValue1() uint64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *AsyncEchoResponse) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

var File_proto_common_msg_login_proto protoreflect.FileDescriptor

var file_proto_common_msg_login_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d,
	0x73, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0x3b, 0x0a, 0x14, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x7c, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x42, 0x0a, 0x1b, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x1c, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x13, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x93, 0x01, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x22, 0x68, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0xb4, 0x01, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x6e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x4e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x72, 0x65, 0x6e, 0x61, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x67,
	0x72, 0x65, 0x6e, 0x61, 0x64, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x3e, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x42, 0x0a, 0x10, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x45,
	0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x43, 0x0a, 0x11, 0x41, 0x73,
	0x79, 0x6e, 0x63, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x42,
	0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x75,
	0x71, 0x75, 0x6e, 0x79, 0x6f, 0x6e, 0x67, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_msg_login_proto_rawDescOnce sync.Once
	file_proto_common_msg_login_proto_rawDescData = file_proto_common_msg_login_proto_rawDesc
)

func file_proto_common_msg_login_proto_rawDescGZIP() []byte {
	file_proto_common_msg_login_proto_rawDescOnce.Do(func() {
		file_proto_common_msg_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_msg_login_proto_rawDescData)
	})
	return file_proto_common_msg_login_proto_rawDescData
}

var file_proto_common_msg_login_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_common_msg_login_proto_goTypes = []interface{}{
	(*HandshakeInitRequest)(nil),         // 0: common_msg.HandshakeInitRequest
	(*HandshakeInitResponse)(nil),        // 1: common_msg.HandshakeInitResponse
	(*HandshakeEstablishedRequest)(nil),  // 2: common_msg.HandshakeEstablishedRequest
	(*HandshakeEstablishedResponse)(nil), // 3: common_msg.HandshakeEstablishedResponse
	(*AccountLoginRequest)(nil),          // 4: common_msg.AccountLoginRequest
	(*AccountLoginResponse)(nil),         // 5: common_msg.AccountLoginResponse
	(*ClientLoginRequest)(nil),           // 6: common_msg.ClientLoginRequest
	(*ClientLoginResponse)(nil),          // 7: common_msg.ClientLoginResponse
	(*EchoRequest)(nil),                  // 8: common_msg.EchoRequest
	(*EchoResponse)(nil),                 // 9: common_msg.EchoResponse
	(*AsyncEchoRequest)(nil),             // 10: common_msg.AsyncEchoRequest
	(*AsyncEchoResponse)(nil),            // 11: common_msg.AsyncEchoResponse
}
var file_proto_common_msg_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_msg_login_proto_init() }
func file_proto_common_msg_login_proto_init() {
	if File_proto_common_msg_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_msg_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeEstablishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeEstablishedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncEchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_msg_login_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncEchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_msg_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_msg_login_proto_goTypes,
		DependencyIndexes: file_proto_common_msg_login_proto_depIdxs,
		MessageInfos:      file_proto_common_msg_login_proto_msgTypes,
	}.Build()
	File_proto_common_msg_login_proto = out.File
	file_proto_common_msg_login_proto_rawDesc = nil
	file_proto_common_msg_login_proto_goTypes = nil
	file_proto_common_msg_login_proto_depIdxs = nil
}
