// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: protobuf/service_discovery.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryStatus int32

const (
	RegistryStatus_RS_None       RegistryStatus = 0
	RegistryStatus_RS_Learning   RegistryStatus = 1
	RegistryStatus_RS_Forwarding RegistryStatus = 2
)

// Enum value maps for RegistryStatus.
var (
	RegistryStatus_name = map[int32]string{
		0: "RS_None",
		1: "RS_Learning",
		2: "RS_Forwarding",
	}
	RegistryStatus_value = map[string]int32{
		"RS_None":       0,
		"RS_Learning":   1,
		"RS_Forwarding": 2,
	}
)

func (x RegistryStatus) Enum() *RegistryStatus {
	p := new(RegistryStatus)
	*p = x
	return p
}

func (x RegistryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_service_discovery_proto_enumTypes[0].Descriptor()
}

func (RegistryStatus) Type() protoreflect.EnumType {
	return &file_protobuf_service_discovery_proto_enumTypes[0]
}

func (x RegistryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistryStatus.Descriptor instead.
func (RegistryStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{0}
}

type UpdateMode int32

const (
	UpdateMode_UM_None        UpdateMode = 0
	UpdateMode_UM_Full        UpdateMode = 1
	UpdateMode_UM_Incremental UpdateMode = 2
)

// Enum value maps for UpdateMode.
var (
	UpdateMode_name = map[int32]string{
		0: "UM_None",
		1: "UM_Full",
		2: "UM_Incremental",
	}
	UpdateMode_value = map[string]int32{
		"UM_None":        0,
		"UM_Full":        1,
		"UM_Incremental": 2,
	}
)

func (x UpdateMode) Enum() *UpdateMode {
	p := new(UpdateMode)
	*p = x
	return p
}

func (x UpdateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_service_discovery_proto_enumTypes[1].Descriptor()
}

func (UpdateMode) Type() protoreflect.EnumType {
	return &file_protobuf_service_discovery_proto_enumTypes[1]
}

func (x UpdateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateMode.Descriptor instead.
func (UpdateMode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{1}
}

type EndPointInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm     uint32       `protobuf:"varint,1,opt,name=realm,proto3" json:"realm,omitempty"`
	Type      EndPointType `protobuf:"varint,2,opt,name=type,proto3,enum=testdata.EndPointType" json:"type,omitempty"`
	Id        uint32       `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Auth      string       `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Ip        string       `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port      uint32       `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	CodecType uint32       `protobuf:"varint,7,opt,name=codec_type,json=codecType,proto3" json:"codec_type,omitempty"`
	MaskFlag  uint32       `protobuf:"varint,8,opt,name=mask_flag,json=maskFlag,proto3" json:"mask_flag,omitempty"`
}

func (x *EndPointInstance) Reset() {
	*x = EndPointInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndPointInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndPointInstance) ProtoMessage() {}

func (x *EndPointInstance) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndPointInstance.ProtoReflect.Descriptor instead.
func (*EndPointInstance) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *EndPointInstance) GetRealm() uint32 {
	if x != nil {
		return x.Realm
	}
	return 0
}

func (x *EndPointInstance) GetType() EndPointType {
	if x != nil {
		return x.Type
	}
	return EndPointType_EPT_None
}

func (x *EndPointInstance) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EndPointInstance) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *EndPointInstance) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EndPointInstance) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndPointInstance) GetCodecType() uint32 {
	if x != nil {
		return x.CodecType
	}
	return 0
}

func (x *EndPointInstance) GetMaskFlag() uint32 {
	if x != nil {
		return x.MaskFlag
	}
	return 0
}

type ConnectDialResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerialNum uint64 `protobuf:"varint,1,opt,name=serial_num,json=serialNum,proto3" json:"serial_num,omitempty"`
	Result    uint32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	LocalIp   string `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
}

func (x *ConnectDialResult) Reset() {
	*x = ConnectDialResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectDialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDialResult) ProtoMessage() {}

func (x *ConnectDialResult) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDialResult.ProtoReflect.Descriptor instead.
func (*ConnectDialResult) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectDialResult) GetSerialNum() uint64 {
	if x != nil {
		return x.SerialNum
	}
	return 0
}

func (x *ConnectDialResult) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ConnectDialResult) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

// 注册服务节点 register
type MSG_REQUEST_REGISTER_INSTANCE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance *EndPointInstance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Auth     string            `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *MSG_REQUEST_REGISTER_INSTANCE) Reset() {
	*x = MSG_REQUEST_REGISTER_INSTANCE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_REQUEST_REGISTER_INSTANCE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_REQUEST_REGISTER_INSTANCE) ProtoMessage() {}

func (x *MSG_REQUEST_REGISTER_INSTANCE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_REQUEST_REGISTER_INSTANCE.ProtoReflect.Descriptor instead.
func (*MSG_REQUEST_REGISTER_INSTANCE) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *MSG_REQUEST_REGISTER_INSTANCE) GetInstance() *EndPointInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *MSG_REQUEST_REGISTER_INSTANCE) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type MSG_RESPONSE_REGISTER_INSTANCE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode      uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ListenersConfig string `protobuf:"bytes,2,opt,name=listeners_config,json=listenersConfig,proto3" json:"listeners_config,omitempty"`
	MysqlConfig     string `protobuf:"bytes,3,opt,name=mysql_config,json=mysqlConfig,proto3" json:"mysql_config,omitempty"`
	NatsConfig      string `protobuf:"bytes,4,opt,name=nats_config,json=natsConfig,proto3" json:"nats_config,omitempty"`
	RedisConfig     string `protobuf:"bytes,5,opt,name=redis_config,json=redisConfig,proto3" json:"redis_config,omitempty"`
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) Reset() {
	*x = MSG_RESPONSE_REGISTER_INSTANCE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_RESPONSE_REGISTER_INSTANCE) ProtoMessage() {}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_RESPONSE_REGISTER_INSTANCE.ProtoReflect.Descriptor instead.
func (*MSG_RESPONSE_REGISTER_INSTANCE) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) GetListenersConfig() string {
	if x != nil {
		return x.ListenersConfig
	}
	return ""
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) GetMysqlConfig() string {
	if x != nil {
		return x.MysqlConfig
	}
	return ""
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) GetNatsConfig() string {
	if x != nil {
		return x.NatsConfig
	}
	return ""
}

func (x *MSG_RESPONSE_REGISTER_INSTANCE) GetRedisConfig() string {
	if x != nil {
		return x.RedisConfig
	}
	return ""
}

type MSG_NOTICE_INSTANCE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version        uint64              `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Status         RegistryStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=testdata.RegistryStatus" json:"status,omitempty"`
	Mode           UpdateMode          `protobuf:"varint,4,opt,name=mode,proto3,enum=testdata.UpdateMode" json:"mode,omitempty"`
	AddInstance    []*EndPointInstance `protobuf:"bytes,5,rep,name=add_instance,json=addInstance,proto3" json:"add_instance,omitempty"`
	DeleteInstance []*EndPointInstance `protobuf:"bytes,6,rep,name=delete_instance,json=deleteInstance,proto3" json:"delete_instance,omitempty"`
	UpdateInstance []*EndPointInstance `protobuf:"bytes,7,rep,name=update_instance,json=updateInstance,proto3" json:"update_instance,omitempty"`
}

func (x *MSG_NOTICE_INSTANCE) Reset() {
	*x = MSG_NOTICE_INSTANCE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_NOTICE_INSTANCE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_NOTICE_INSTANCE) ProtoMessage() {}

func (x *MSG_NOTICE_INSTANCE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_NOTICE_INSTANCE.ProtoReflect.Descriptor instead.
func (*MSG_NOTICE_INSTANCE) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *MSG_NOTICE_INSTANCE) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MSG_NOTICE_INSTANCE) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MSG_NOTICE_INSTANCE) GetStatus() RegistryStatus {
	if x != nil {
		return x.Status
	}
	return RegistryStatus_RS_None
}

func (x *MSG_NOTICE_INSTANCE) GetMode() UpdateMode {
	if x != nil {
		return x.Mode
	}
	return UpdateMode_UM_None
}

func (x *MSG_NOTICE_INSTANCE) GetAddInstance() []*EndPointInstance {
	if x != nil {
		return x.AddInstance
	}
	return nil
}

func (x *MSG_NOTICE_INSTANCE) GetDeleteInstance() []*EndPointInstance {
	if x != nil {
		return x.DeleteInstance
	}
	return nil
}

func (x *MSG_NOTICE_INSTANCE) GetUpdateInstance() []*EndPointInstance {
	if x != nil {
		return x.UpdateInstance
	}
	return nil
}

type MSG_REQUEST_HEARTBEAT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MSG_REQUEST_HEARTBEAT) Reset() {
	*x = MSG_REQUEST_HEARTBEAT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_REQUEST_HEARTBEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_REQUEST_HEARTBEAT) ProtoMessage() {}

func (x *MSG_REQUEST_HEARTBEAT) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_REQUEST_HEARTBEAT.ProtoReflect.Descriptor instead.
func (*MSG_REQUEST_HEARTBEAT) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{5}
}

type MSG_RESPONSE_HEARTBEAT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *MSG_RESPONSE_HEARTBEAT) Reset() {
	*x = MSG_RESPONSE_HEARTBEAT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_discovery_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_RESPONSE_HEARTBEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_RESPONSE_HEARTBEAT) ProtoMessage() {}

func (x *MSG_RESPONSE_HEARTBEAT) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_discovery_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_RESPONSE_HEARTBEAT.ProtoReflect.Descriptor instead.
func (*MSG_RESPONSE_HEARTBEAT) Descriptor() ([]byte, []int) {
	return file_protobuf_service_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *MSG_RESPONSE_HEARTBEAT) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_protobuf_service_discovery_proto protoreflect.FileDescriptor

var file_protobuf_service_discovery_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x15, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x10, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x2a,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x73, 0x6b, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x65,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x49, 0x70, 0x22, 0x6b, 0x0a, 0x1d, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x49, 0x4e,
	0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x12, 0x36, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x22, 0xd3, 0x01, 0x0a, 0x1e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x53,
	0x54, 0x41, 0x4e, 0x43, 0x45, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xe4, 0x02, 0x0a, 0x13, 0x4d, 0x53, 0x47,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45,
	0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0x17, 0x0a, 0x15, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x48,
	0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x22, 0x39, 0x0a, 0x16, 0x4d, 0x53, 0x47, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45,
	0x41, 0x54, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x2a, 0x41, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x53, 0x5f, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x53, 0x5f, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x53, 0x5f, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x2a, 0x3a, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4d, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4d, 0x5f, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x55, 0x4d, 0x5f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x10, 0x02, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x75, 0x71, 0x75, 0x6e, 0x79, 0x6f, 0x6e, 0x67, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_service_discovery_proto_rawDescOnce sync.Once
	file_protobuf_service_discovery_proto_rawDescData = file_protobuf_service_discovery_proto_rawDesc
)

func file_protobuf_service_discovery_proto_rawDescGZIP() []byte {
	file_protobuf_service_discovery_proto_rawDescOnce.Do(func() {
		file_protobuf_service_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_service_discovery_proto_rawDescData)
	})
	return file_protobuf_service_discovery_proto_rawDescData
}

var file_protobuf_service_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_service_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_service_discovery_proto_goTypes = []interface{}{
	(RegistryStatus)(0),                    // 0: testdata.RegistryStatus
	(UpdateMode)(0),                        // 1: testdata.UpdateMode
	(*EndPointInstance)(nil),               // 2: testdata.EndPointInstance
	(*ConnectDialResult)(nil),              // 3: testdata.ConnectDialResult
	(*MSG_REQUEST_REGISTER_INSTANCE)(nil),  // 4: testdata.MSG_REQUEST_REGISTER_INSTANCE
	(*MSG_RESPONSE_REGISTER_INSTANCE)(nil), // 5: testdata.MSG_RESPONSE_REGISTER_INSTANCE
	(*MSG_NOTICE_INSTANCE)(nil),            // 6: testdata.MSG_NOTICE_INSTANCE
	(*MSG_REQUEST_HEARTBEAT)(nil),          // 7: testdata.MSG_REQUEST_HEARTBEAT
	(*MSG_RESPONSE_HEARTBEAT)(nil),         // 8: testdata.MSG_RESPONSE_HEARTBEAT
	(EndPointType)(0),                      // 9: testdata.EndPointType
}
var file_protobuf_service_discovery_proto_depIdxs = []int32{
	9, // 0: testdata.EndPointInstance.type:type_name -> testdata.EndPointType
	2, // 1: testdata.MSG_REQUEST_REGISTER_INSTANCE.instance:type_name -> testdata.EndPointInstance
	0, // 2: testdata.MSG_NOTICE_INSTANCE.status:type_name -> testdata.RegistryStatus
	1, // 3: testdata.MSG_NOTICE_INSTANCE.mode:type_name -> testdata.UpdateMode
	2, // 4: testdata.MSG_NOTICE_INSTANCE.add_instance:type_name -> testdata.EndPointInstance
	2, // 5: testdata.MSG_NOTICE_INSTANCE.delete_instance:type_name -> testdata.EndPointInstance
	2, // 6: testdata.MSG_NOTICE_INSTANCE.update_instance:type_name -> testdata.EndPointInstance
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_service_discovery_proto_init() }
func file_protobuf_service_discovery_proto_init() {
	if File_protobuf_service_discovery_proto != nil {
		return
	}
	file_protobuf_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_service_discovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndPointInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectDialResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_REQUEST_REGISTER_INSTANCE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_RESPONSE_REGISTER_INSTANCE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_NOTICE_INSTANCE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_REQUEST_HEARTBEAT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_discovery_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_RESPONSE_HEARTBEAT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_service_discovery_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_service_discovery_proto_goTypes,
		DependencyIndexes: file_protobuf_service_discovery_proto_depIdxs,
		EnumInfos:         file_protobuf_service_discovery_proto_enumTypes,
		MessageInfos:      file_protobuf_service_discovery_proto_msgTypes,
	}.Build()
	File_protobuf_service_discovery_proto = out.File
	file_protobuf_service_discovery_proto_rawDesc = nil
	file_protobuf_service_discovery_proto_goTypes = nil
	file_protobuf_service_discovery_proto_depIdxs = nil
}
